function update_website_names(){ // updates dock labels
    // left dock
    // lowercase: labels
    $('#ld-a').text(label_a)
    $('#ld-b').text(label_b)
    $('#ld-c').text(label_c)
    $('#ld-d').text(label_d)
    $('#ld-e').text(label_e)
    $('#ld-f').text(label_f)
    $('#ld-g').text(label_g)
    $('#ld-h').text(label_h)
    $('#ld-i').text(label_i)
    $('#ld-j').text(label_j)
    $('#ld-k').text(label_k)
    $('#ld-l').text(label_l)
    $('#ld-m').text(label_m)
    $('#ld-n').text(label_n)
    $('#ld-o').text(label_o)
    $('#ld-p').text(label_p)
    $('#ld-q').text(label_q)
    $('#ld-r').text(label_r)
    $('#ld-s').text(label_s)
    $('#ld-t').text(label_t)
    $('#ld-u').text(label_u)
    $('#ld-v').text(label_v)
    $('#ld-w').text(label_w)
    $('#ld-x').text(label_x)
    $('#ld-y').text(label_y)
    $('#ld-z').text(label_z)

    // UPPERCASE: labels
    $('#ld-A').text(label_A)
    $('#ld-B').text(label_B)
    $('#ld-C').text(label_C)
    $('#ld-D').text(label_D)
    $('#ld-E').text(label_E)
    $('#ld-F').text(label_F)
    $('#ld-G').text(label_G)
    $('#ld-H').text(label_H)
    $('#ld-I').text(label_I)
    $('#ld-J').text(label_J)
    $('#ld-K').text(label_K)
    $('#ld-L').text(label_L)
    $('#ld-M').text(label_M)
    $('#ld-N').text(label_N)
    $('#ld-O').text(label_O)
    $('#ld-P').text(label_P)
    $('#ld-Q').text(label_Q)
    $('#ld-R').text(label_R)
    $('#ld-S').text(label_S)
    $('#ld-T').text(label_T)
    $('#ld-U').text(label_U)
    $('#ld-V').text(label_V)
    $('#ld-W').text(label_W)
    $('#ld-X').text(label_X)
    $('#ld-Y').text(label_Y)
    $('#ld-Z').text(label_Z)

    // right dock
    // numbers: labels
    $('#rd-0').text(label_0)
    $('#rd-1').text(label_1)
    $('#rd-2').text(label_2)
    $('#rd-3').text(label_3)
    $('#rd-4').text(label_4)
    $('#rd-5').text(label_5)
    $('#rd-6').text(label_6)
    $('#rd-7').text(label_7)
    $('#rd-8').text(label_8)
    $('#rd-9').text(label_9)
    console.log('dock website names updated!')
}
